#!/bin/bash

read -p "This installs lots of stuff. Continue (y/*)?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # snap
    sudo apt install snapd

    # probably already have some of these, but make sure
    sudo apt-get install zsh curl git

    # zsh default shell / oh my zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    # zsh syntax highlighting
    cd $HOME/.oh-my-zsh/custom/plugins/
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
    cd $HOME

    # spacemacs
    sudo snap install emacs --classic
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    cd $HOME/.emacs.d
    git checkout develop
    cd $HOME
    mkdir -p bin
    ln -s $HOME/dotfiles/scripts/ec $HOME/bin/ec

    # ripgrep
    curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
    sudo dpkg -i ripgrep_11.0.2_amd64.deb
    rm ripgrep_11.0.2_amd64.deb

    # bat
    wget https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb
    sudo dpkg -i bat_0.12.1_amd64.deb
    rm bat_0.12.1_amd64.deb

    # nemo instead of nautilus
    sudo apt install nemo
    xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
    gsettings set org.gnome.desktop.background show-desktop-icons false
    gsettings set org.nemo.desktop show-desktop-icons true

    # set up symlinks to dotfiles
    cd $HOME/dotfiles/scripts/
    ./setup

fi
